### ISSUE TITLE
y_harm and y_perc switched in segmenter.py

### ISSUE THREAD

**Issue by ctralie** [bmcfee/laplacian_segmentation#1]
Hi!
I was just trying out some of your code and I noticed listening to y_perc and y_harm that they sounded switched.  And indeed, in your current documentation of librosa you have them in the reverse order that they appear on line 131 of segmenter.py.  Perhaps they got switched in a newer version of librosa?

Anyway, maybe this doesn't matter anymore, but I figured I'd flag it just in case.

Thanks for the great software!
Sincerely,
Chris Tralie

**Comment by ctralie** [comment]
I should also say this seems to have a pretty huge impact on the quality of the beat tracking and the recurrence plots

**Comment by bmcfee** [comment]
O_O

Wow, how embarrassing!  Thanks for catching that.

It looks like this reversal even predates the refactor I did after ismir, in which the code was switched over from raw stft ops to use the `effects` module.

I'll push a patch in a minute here.

**Comment by ctralie** [comment]
The wonders of open source :)
This is why I really appreciate researchers who keep their source code up online and who are willing to fix mistakes that are found by the community, so we all know exactly what's going on and we can reproduce things.  I wish more people were like that.  So thank you
Best,
Chris Tralie

**Comment by bmcfee** [comment]
No problem!  Likewise, I really appreciate it when people find my bugs for me. :)  I'm just sorry this code wasn't better documented and tested.

I'm currently re-running the experiments from the paper, and will put up a short correction once all the figures are in.

Thanks again!

**Comment by bmcfee** [comment]
Quick update:

The Beatles results (table 1) should be amended as follows:

``` tex
Method & $F_{0.5}$ & $F_3$ & $F_\text{pair}$\\
\midrule
$L_2$   & 0.322 $\pm$ 0.15 & 0.469 $\pm$ 0.19   & 0.590 $\pm$ 0.14\\
$L_3$   & 0.345 $\pm$ 0.20 & 0.579 $\pm$ 0.16   & 0.618 $\pm$ 0.13\\
$L_4$   & 0.323 $\pm$ 0.16 & 0.566 $\pm$ 0.15   & 0.595 $\pm$ 0.13\\
$L_5$   & 0.313 $\pm$ 0.15 & 0.550 $\pm$ 0.14   & 0.562 $\pm$ 0.13\\
$L_6$   & 0.294 $\pm$ 0.14 & 0.510 $\pm$ 0.14   & 0.524 $\pm$ 0.13\\
$L_7$   & 0.269 $\pm$ 0.13 & 0.461 $\pm$ 0.24   & 0.488 $\pm$ 0.19\\
$L_8$   & 0.258 $\pm$ 0.12 & 0.426 $\pm$ 0.12   & 0.454 $\pm$ 0.12\\
$L_9$   & 0.229 $\pm$ 0.11 & 0.393 $\pm$ 0.12   & 0.420 $\pm$ 0.11\\
$L_{10}$& 0.222 $\pm$ 0.11 & 0.367 $\pm$ 0.11   & 0.394 $\pm$ 0.11\\
\midrule
$L$     & 0.344 $\pm$ 0.17 & 0.594 $\pm$ 0.16   & 0.623 $\pm$ 0.13\\
$L^*$   & 0.455 $\pm$ 0.14 & 0.682 $\pm$ 0.13   & 0.685 $\pm$ 0.12\\

```

**Comment by dpwe** [comment]
Is that better?  Do we want it to be better?

  DAn.

**Comment by bmcfee** [comment]
For the most part, yeah, it's better.  The raw results show it more clearly, we pick up mainly in boundary recall (not so much with frame labeling).  It also expands the range of the scores for fixed values of m (L_2 does better than before, L_10 does worse than before).

**Comment by ctralie** [comment]
Nice!  I'm glad it improved.  I was mainly interested in what the structure matrix looked like.  The thing I noticed right away when swapping them was that the beat detection seemed to be more accurate, at least in the example I looked at.
