### ISSUE TITLE
About the label_entropy function in segmenter.py

### ISSUE THREAD

**Issue by wangsix** [bmcfee/laplacian_segmentation#2]
I am working on the music segmentation problem and I have a few questions about your code when I studied it. It would be great if you could give some pointers.

The function label_entropy in segmenter.py returns the entropy of the "labels" but not the hits calculated inside the function. Is this intended? Then, if it was the "hits" that was intended to be used.
Wouldn`t it always return 1.0 after divided by log(k)? Because of the np.unique function only returns the unique value of an array, it is somewhat effectively the same as range(k) in some sense. Then the next for loop in the function will just fill hits with one count for each bin.

Please let me know if I misunderstood anything or missed some steps you
took in the code. Thank you so much!!!

**Comment by bmcfee** [comment]
> The function label_entropy in segmenter.py returns the entropy of the "labels" but not the hits calculated inside the function. Is this intended?

`labels` is a parameter of `label_entropy`.  If you look down to where it gets called, you should find [this bit](https://github.com/bmcfee/laplacian_segmentation/blob/master/code/segmenter.py#L495-L506).

What's going on is that it's building a clustering object `C` to partition the graph, and then `C` assigns each vertex (i.e., beat) to a cluster label.  This is done repeatedly for different numbers of clusters (`n_types` in the snippet above), and the resulting entropy score is used to select the final partitioning from all candidates.

Inside `label_entropy`, the `hits` variable is just used to compute the statistics of label usage.  `hits[k]` is the fraction of beats assigned to label `k`.  It won't always be 1.0.

I hope this clarifies things for you!

**Comment by wangsix** [comment]
I am still a bit confused about the `label_entropy` function since at the end of that function it returns directly `scipy.stats.entropy(labels)` without the `hits` being used at all. 

The other thing is still about how the hits are calculated. Isn't `np.unique` returns only the unique items in an array? 

```
>>> np.unique([1,1,2,2,1,1])
array([1,2])
```

**Comment by bmcfee** [comment]
> I am still a bit confused about the label_entropy function since at the end of that function it returns directly scipy.stats.entropy(labels) without the hits being used at all.

Hoooo yeah, that indeed looks like a bug!  Thanks for catching that.  I'll patch it.

> The other thing is still about how the hits are calculated. Isn't np.unique returns only the unique items in an array?

Yes, but `hits` is just using `unique` to figure out the set of labels.  The loop then fills in the values by counting up how many beats have that value.

**Comment by bmcfee** [comment]
It should be fixed now.

**Comment by wangsix** [comment]
Sorry if this back and forth is bothering, but I thought since the for loop is iterating over `values`, each bin in `hits` will only have one count. Maybe... the `value==v` should be `labels==v`?

**Comment by bmcfee** [comment]
... yup, correct again.  Man, where were you last year when I first hacked this thing out? :)

Thanks!  That one is fixed as well now.

At any rate, I don't think the label entropy heuristic is particularly good (or well-motivated) anyway, but your mileage may vary.

**Comment by wangsix** [comment]
Thank you for all the responses!! I am trying to catching up in the field so these feedbacks are beneficial for me! Your works have been one of the most resourceful place I look into when trying to solve problems.

I am currently adopting your spectral clustering approach but with a different way to generate the linkage/connectivity matrix in the first place. I have tried a few different heuristics in terms of finding the `k` for the k-means clustering, none of them is generalizable to the dataset so far, and it seems like fixing `k` with a value between 4~6 in general works... 

Please say hi for me to Prof. Bello, I really missed his advisement, and hope to talk to you in person (maybe ISMIR?).

**Comment by bmcfee** [comment]
> and it seems like fixing k with a value between 4~6 in general works...

This is going to depend on the corpus, but i seem to remember at one point calculating the distribution of segment labels (per track) in beatles-tut and it having a peak at 5.  I expect other pop-oriented corpora with similar annotation rules to show similar behavior.  SALAMI was more of a mixed bag, but that's why I like to test at multiple resolutions (ie large and small).

**Comment by urinieto** [comment]
I updated the code in [msaf](https://github.com/urinieto/msaf/commit/f7d86fe8984864197754acb33a69fb2fceac1d2d) accordingly, thanks for reporting this Cheng-i!

A quick benchmark using Iso The Beatles dataset with ground truth boundaries:
before Pairwise Frame Clustering F-measure: 75%
now Pairwise Frame Clustering F-measure: 78%
