### ISSUE TITLE
Structural Segmentation of music

### ISSUE THREAD

**Issue by surajsonee** [bmcfee/laplacian_segmentation#5]
Do i get the structural parts of music like intro, chorus, verse, bridge and outro.
Thanks!

**Comment by bmcfee** [comment]
Yes, but this repo is mainly for the paper and prototype implementation.  You'd probably be better off using the https://github.com/urinieto/msaf implementation.

**Comment by surajsonee** [comment]
> Yes, but this repo is mainly for the paper and prototype implementation. You'd probably be better off using the https://github.com/urinieto/msaf implementation

yes I have used MSAF, the result is not good.
that's why i come here in your code.

can you please let me know how i can print start time and end time of intro, chorus, verse, bridge and outro.
